ls
create table tvp_cartoon_series as select tvp.* from tbl_tv_program as tvp, tbl_tv_program_tv_genre as tvp_tvg, tbl_tv_genre as tvg
create table tvp_comedy_film as select tvp.* from tvl_tv_program as tvp, tvl_tv_program_tv_genre as tvp_tvg, tvl_tv_genre as tvg where tvp.id = tvp_cs.id where tvp_cs.id is null;
create table tvp_comedy_film as select tvp.* from tvl_tv_program as tvp, tvp_tv_program_tv_genre as tvp_tvg, tvp_tv_genre as tvg where tvp.id = tvp_tvg.tv_program and tvp_tvg.tv_genre = tvg.id and tvg.name like 'Comedy film';
create table tvp_comedy_film as select tvp.* from tvp_tv_program as tvp, tvp_tv_program_tv_genre as tvp_tvg, tvp_tv_genre as tvg where tvp.id = tvp_tvg.tv_program and tvp_tvg.tv_genre = tvg.id and tvg.name like 'Comedy film';
create table tvp_comedy_film as select tvp.* from tbl_tv_program as tvp, tbl_tv_program_tv_genre as tvp_tvg, tbl_tv_genre as tvg where tvp.id = tvp_tvg.tv_program and tvp_tvg.tv_genre = tvg.id and tvg.name like 'Comedy film';
create table tvp_not_comedy_film as select tvp.* from tvl_tv_program as tvp left join tvp_comedy_film as tvp_cf on tvp.id = tvp_cf.id where tvp_cf.id is null;
create table qrel as select query.*, tbl_all.name, tbl_all.description 
create table qrel as select query.*, tbl_all.name, tbl_all.description  from query, tbl_all where query.fbid = tbl_all.fbid;
create table tbl_all as
create table tbl_all as         select p.id, p.fbid, p.name, p.description, 'person' as `semantic_type` from tbl_person as p                  union (select tvp.id, tvp.fbid, tvp.name, tvp.description, 'tv_program' as `semantic_type` from tbl_tv_program as tvp)                 union (select f.id, f.fbid, f.name, f.description, 'film' as `semantic_type` from tbl_film as f)                 union (select pl.id, pl.fbid, pl.name, pl.description, 'play' as `semantic_type` from tbl_play as pl)                 union (select al.id, al.fbid, al.name, al.description, 'album' as `semantic_type` from tbl_album as al)                 union (select b.id, b.fbid, b.name, b.description, 'book' as `semantic_type` from tbl_book as b)                 union (select g.id, g.fbid, g.name, g.description, 'game' as `semantic_type` from tbl_game as g)                 union (select o.id, o.fbid, o.name, o.description, 'opera' as `semantic_type` from tbl_opera as o);
create table tbl_all as
create table tbl_all as         select p.id, p.fbid, p.name, p.description, 'person' as `semantic_type` from tbl_person as p                  union (select tvp.id, tvp.fbid, tvp.name, tvp.description, 'tv_program' as `semantic_type` from tbl_tv_program as tvp)                 union (select f.id, f.fbid, f.name, f.description, 'film' as `semantic_type` from tbl_film as f)                 union (select pl.id, pl.fbid, pl.name, pl.description, 'play' as `semantic_type` from tbl_play as pl)                 union (select al.id, al.fbid, al.name, al.description, 'album' as `semantic_type` from tbl_album as al)                 union (select b.id, b.fbid, b.name, b.description, 'book' as `semantic_type` from tbl_book as b)                 union (select g.id, g.fbid, g.name, g.description, 'game' as `semantic_type` from tbl_game as g)                 union (select o.id, o.fbid, o.name, o.description, 'opera' as `semantic_type` from tbl_opera as o);
load data local infile '/scratch/data-set/cunts2' into table inex_count fields terminated by ' ';
load data local infile '/scratch/data-set/cunts2' into table inex_count fields terminated by ' ';
load data infile '/scratch/data-set/cunts2' into table inex_count fields terminated by ' ';
create table tmp_article_link_1 as select al.* from tbl_article_link_09 al join tbl_article_wiki13 a on al.article_id = a.id;
create table tmp_article_link_1 as select al.* from tbl_article_link_09 al join tbl_article_wiki13 a on al.article_id = a.id;
create table tmp_article_link_1 as select al.* from tbl_article_link_09 al join tmp_article_1 a on al.article_id = a.id;
create table tmp_article_image_1 as select al.* from tbl_article_image_09 al join tmp_article_1 a on al.article_id = a.id;
ls
create database wikipedia;
create table wiki[Bpedia.mem_image_image as select distict i.* from tbl_image_09 i join sub_article s on s.id = i.article_id;
create database mem_wikipedia;
create table mem_wikipedia.mem_image_image as select distict i.* from wikipedia.tbl_image_09 i join wikipedia.sub_article s on s.id = i.article_id;
create table mem_wikipedia.mem_image_image as select distinct i.* from wikipedia.tbl_image_09 i join wikipedia.sub_article s on s.id = i.article_id;
create table mem_wikipedia.mem_image_image as select distinct ii.* from wikipedia.tbl_image_09 ii join wikipedia.sub_image i on ii.id = i.image_id;
create table mem_wikipedia.mem_link_link as select distinct ll.* from wikipedia.tbl_link_09 ll join wikipedia.sub_link l on ll.id = l.image_id;
create table mem_wikipedia.mem_link_link as select distinct ll.* from wikipedia.tbl_link_09 ll join wikipedia.sub_link l on ll.id = l.link_id;
alter table mem_wikipeda.mem_image_image rename wikipedia.mem_image_image;
alter table mem_wikipedia.mem_image_image rename wikipedia.mem_image_image;
alter table wikipedia.mem_link_link add primary key(id);
alter table wikipedia.mem_image_image add primary key(id);
alter table wikipedia.mem_image_image alter column caption varchar(255);
alter table wikipedia.mem_image_image alter column caption varchar;
alter table wikipedia.mem_image_image modify column caption varchar(255);
alter table wikipedia.mem_link_link engine=MEMORY;
alter table wikipedia.mem_image_image engine=MEMORY;
ls
create table wikipedia.sub_like wikipedia.tbl_article;
create table wikipedia.sub_article_16 like wikipedia.tbl_article;
create table wikipedia.sub_article_16 like wikipedia.tbl_article_wiki13;
create table wikipedia.sub_image_16 like wikipedia.tbl_article_image;
create table wikipedia.sub_image_16 like wikipedia.tbl_article_image_09;
create mem_article_16 like sub_article_16;
create wikipedia.mem_article_16 like wikipedia.sub_article_16;
create table wikipedia.mem_article_16 like wikipedia.sub_article_16;
create table wikipedia.mem_link_link_16 like wikipedia.tbl_link_09;
alter table wikipedia.mem_article_16 modify column title varchar(255);
alter table wikipedia.mem_article_16 modify column test varchar();
alter table wikipedia.mem_article_16 modify column test varchar;
alter table wikipedia.mem_article_16 modify column test varchar(61000);
alter table wikipedia.mem_article_16 modify column text varchar;
alter table wikipedia.mem_article_16 modify column text varchar(61000);
alter table wikipedia.mem_article_16 drop column text_wiki09;
alter table wikipedia.mem_article_16 modify column text varchar(60000);
alter table wikipedia.mem_article_16 modify column text varchar(60000);
alter table wikipedia.mem_article_16 modify column text varchar(65000);
alter table wikipedai.mem_article_16 modify column text varchar(32000);
alter table wikipedia.mem_article_16 modify column text varchar(32000);
alter table wikipedia.mem_article_16 modify column text varchar(32000);
alter table wikipedia.mem_article_16 rename column text tx;
alter table wikipedia.mem_article_16 rename text tx;
alter table wikipedia.mem_article_16 change text tx varchar(31000);
alter table wikipedia.mem_article_16 modify tx varchar(31000);
alter table wikipedia.mem_article_16 modify tx varchar(31000);
alter table wikipedia.mem_article_16 modify tx varchar(31000);
alter table wikipedia.mem_article_16 modify tx varchar(256);
alter table mem_article_16 engine=memory;
alter table wikipedia.mem_article_16 engine=memory;
alter table wikipedia.mem_article_16 drop column title;
alter table wikipedia.mem_article_16 drop column tx;
alter table wikipedia.mem_article_16 engine=memory;
rename wikipedia.sub_link_16 wikipedia.mem_link_16; 
rename wikipedia.sub_link_16 to wikipedia.mem_link_16; 
rename table wikipedia.sub_link_16 to wikipedia.mem_link_16; 
alter table wikipedia.mem_link_16 engine=memory;
alter table wikipedia.mem_link_16 engine=memory;
alter table wikipedia.mem_link_16 engine=memory;
create database abtin;
create user 'khodadaa'@'localhost' identified by 'OdKRFDQ6FHR1KXU7';
rename table sub_image_16 to mem_image_16;
rename table wikipedia.sub_image_16 to wikipedia.mem_image_16;
alter table wikipedia.mem_image_16 engine=memory;
alter table wikipedia.mem_link_link_16 engine=memory;
create table wikipedia.mem_image_image_16 like wikipedia.tbl_image_09;
explain SELECT a.id FROM wikipedia.mem_article_16 a left join wikipedia.mem_image_16 i on a.id = i.article_id where a.id in (92699);
explain select * from wikipedia.mem_image_16 i where i.article_id = 92699;
explain select * from wikipedia.mem_image_16 i where i.image_id = 883817;
alter table wikipedia.mem_image_16 add primary key (article_id, image_id);
analyze table wikipedia.mem_image_16;
analyze table wikipedia.mem_image_16;
alter table mem_image_16 drop index primary;
alter table mem_image_16 drop index PRIMARY;
alter table mem_article_image_1 add primary key (article_id, image_id);
create index aid on mem_image_16 int(11);
create index `aid` on mem_image_16 int(11);
create index `aid` on mem_image_16;
create index `aid` on mem_image_16.article_id;
create index `aid` on mem_image_16 article_id(11);
create index `aid` on mem_image_16 article_id;
create index `aid` on mem_image_16(article_id);
explain select * from wikipedia.mem_image_16 i where i.image_id = 883817;
create index `aid` on mem_link_16(article_id);
rename table mem_article to mem_article_1;
rename table mem_image to mem_article_image_1;
rename table mem_link to mem_article_link_1;
rename table mem_image_16 to mem_article_image_16;
rename table mem_image_image to mem_image;
rename table mem_image_image_16 mem_image_16;
rename table mem_image_image_16 to mem_image_16;
rename tbale mem_image to mem_image_1;
rename table mem_image to mem_image_1;
rename table mem_link_16 to mem_article_link_16;
rename table mem_link_link to mem_link_1;
rename table me_link_link_16 to mem_link_16;
rename table mem_link_link_16 to mem_link_16;
create index `aid` on mem_article_image_1(article_id);
create index `aid` on mem_article_link_1(article_id);
create index `aid` on mem_article_link_16(article_id);
create index `aid` on mem_article_link_16(article_id);
create index `aid` on mem_article_link_16(article_id);
create index `aid` on mem_article_link_16(article_id);
create table den_article_image_1 as select mem_article_1 a left join mem_article_image_1 i on a.id = i.article_id left join mem_article ii on ii.id = i.image_id;
create table den_article_image_1 as select a.*, i.image_id, ii.im mem_article_1 a left join mem_article_image_1 i on a.id = i.article_id left join mem_article ii on ii.id = i.image_id;
create table den_article_image_1 as select a.*, i.image_id, ii.src from mem_article_1 a left join mem_article_image_1 i on a.id = i.article_id left join mem_article ii on ii.id = i.image_id;
create table den_article_image_1 as select a.*, i.image_id, ii.src from mem_article_1 a left join mem_article_image_1 i on a.id = i.article_id left join mem_image_1 ii on ii.id = i.image_id;
create table den_article_link_1 as select a.*, i.link_id, ii.xlink_href from mem_link_1 a left join mem_link_image_1 i on a.id = i.article_id left join mem_link_1 ii on ii.id = i.link_id;
create table den_article_link_1 as select a.*, i.link_id, ii.xlink_href from mem_link_1 a left join mem_article_link_1 i on a.id = i.article_id left join mem_link_1 ii on ii.id = i.link_id;
create table den_article_link_1 as select a.*, i.link_id, ii.xlink_href from mem_article_1 a left join mem_article_link_1 i on a.id = i.article_id left join mem_link_1 ii on ii.id = i.link_id;
alter table den_article_link_1 create primary key(id);
alter table den_article_link_1 add primary key(id);
alter table den_article_link_1 add primary key(id);
alter table den_article_link_1 add index key(id);
alter table den_article_link_1 add index(id);
alter table den_article_image_1 add index(id);
create table den_1 as select i.*, l.
create table den_1 as select i.*, l.link_id from den_article_image_1 i left join den_article_link_1 l on i.id = l.id;
rename sub_article sub_article_1;
rename table sub_article to  sub_article_1;
rename table sub_image to sub_image_1;
rename table sub_link to sub_link_1;
rename table sub_link_1 to sub_article_link_1;
rename table sub_image_1 to sub_article_image_1;
alter table mem_article_1 engine=InnoDB;
alter table mem_article_16 engine=InnoDB;
alter table mem_article_image_1 engine=InnoDB;
alter table mem_article_image_16 engine=InnoDB;
alter table mem_article_link_1 engine=InnoDB;
ls
alter table mem_image_1 engine=InnoDB;
alter table mem_image_16 engine=InnoDB;
alter table mem_link_1 engine=InnoDB;
alter table mem_link_16 engine=InnoDB;
ls
alter table sub_article_16 engine=InnoDB;
create database stack_overflow;
create table stack_overflow.questions as select * from Posts where PostTypeId=1;
create table stack_overflow.questions as select * from Posts where PostTypeId=1;
create table stack_overflow.answers as select * from Posts where PostTypeId=2;
create table accepted_answers as select answers.* from answers left join questions on answers.Id = questions.AcceptedAnswerId;
alter table questions add primary key(Id);
alter table questions add primary key(Id);
alter table questions add key(Id);
alter table answers add primary key(Id);
alter table questions drop key(Id);
alter table questions drop key Id;
alter table questions add primary key(Id);
create table question like questions;
alter table question add primary key(Id);
alter table answers add key(Id);
create index on answers (id);
create index on answers(id);
create index on answers(Id(11));
alter table answers add constraint answers_pk primary key (Id);
create unique index on answers(Id);
altern table answers add index (Id);
altern table answers add index(Id);
altern table answers add index(`Id`);
create table answer like answers;
alter table answer add primary key(Id);
create unique index answer_parentid on answer(parent_id);
create unique index answer_parentid on answer(ParentId);
create unique index question_aaid on question(AcceptedanswerId);
create index question_aaid on question(AcceptedanswerId);
create table acc_answer like answer;
create unique index answers_parentid on answers(ParentId);
create index answers_parentid on answers(ParentId);
create index answers_pk on answers(Id);
rename table acc_answer to acc_answers;
alter table acc_answer drop index answer_parentid;
alter table acc_answers drop index answer_parentid;
create table answers_s_train select a.*, t.ViewCount from answers_s a join train t on answers.Id = question.AcceptedAnswerId;
create table acc_questions like questions;
create table acc_questions like question;
rename table question to questions;
create table qa (qid int(11), aid int(11));
load data infile "~/workspace/maple/all.csv" into table qa columns terminated by ',' lines terminated by '\n';
load data infile "/nfs/stak/users/ghadakcv/workspace/maple/all.csv" into table qa columns terminated by ',' lines terminated by '\n';
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/all.csv" into table qa columns terminated by ',' lines terminated by '\n';
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/all.csv" into table qa columns terminated by ',' lines terminated by '\n';
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/so.csv" into table qa columns terminated by ',' lines terminated by '\n';
alter table qa dete
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/so.csv" into table qa columns terminated by ',' lines terminated by '\n';
alter table qa add unique index aid_index (aid);
alter table qa add unique index aid_index (aid);
alter table qa add unique index qid_index (qid);
create table qa_popularity as select qa.*, a.PageCount from qa, answers a where qa.aid = a.Id;
create table qa_popularity as select qa.*, a.ViewCount from qa, answers a where qa.aid = a.Id;
ls
ls
create table qa_viewcount as select qa.*, q.ViewCount from qa, questions q where qa.qid = q.Id;
create table answers_s as select qa_viewcount.*, answers.Body from qa, answers a where qa.aid = a.Id;
create table answers_s as select qa.*, answers.Body from qa_viewcount qa, answers a where qa.aid = a.Id;
create table answers_s as select qa.*, a.Body from qa_viewcount qa, answers a where qa.aid = a.Id;
create table questions_s as select qa.qid, q.Title, qa.ViewCount from qa_viewcount qa, questions q where qa.qid = q.Id;
create table questions_s as select qa.qid, q.Title, q.AcceptedAnswerId, qa.ViewCount from qa_viewcount qa, questions q where qa.qid = q.Id;
rename acc_answers to answers_accepted;
rename table acc_answers to answers_accepted;
rename table acc_questions to questions_accepted;
alter table answers_s change columns `aid` `Id`;
alter table `answers_s` change columns `aid` `Id`;
alter table `answers_s` change column `aid` `Id`;
alter table `answers_s` change column `aid` `Id` int(11) NOT NULL;
alter table `answers_s` change column `qid` `ParentId` int(11) NOT NULL;
create table answers_a as select a.Id, a.Body, a.ParentId, q.ViewCount from answers_accepted a, questions_accepted q where a.ParentId = q.Id;
create table answers_aa as select a.Id, a.Bo
rename table questions_accepted to questions_a;
create table train (Id, int(11), ViewCount int(11));
create table train (id int(11), viewcount int(11));
create table test (id int(11), viewcount int(11));
load data infile '/nfs/stak/users/ghadakcv/workspace/maple/id_train'
load data infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_train" into table train;
load data infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_train" into table train columns terminated by ',' optionally enclosed by '"' escaped by '"' lines terminated by '\n';
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_train" into table train;
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_test" into table test;
create table answers_aa as select a.Id, a.Body, a.ParentId, t.viewcount from answers_a a, train q where a
alter table train add unique index vc_index (viewcount);
alter table train drop index vc_index (viewcount);
alter table train drop index vc_index;
alter table train drop index t_index (id);
alter table train add unique index t_index (id);
alter table test add unique index t_index (id);
create tablecreate table answers_aa as select a.Id, a.Body, a.ParentId, t.viewcount from answers_a a, train t where a.ParentId = t.id;
alter table `train` change column `viewcount` `ViewCount` int(11);
alter table `test` change column `viewcount` `ViewCount` int(11);
alter table `answers_aa` change column `viewcount` `ViewCount` int(11);
create table questions_aa as select a.Id, a.Body, a.ParentId, t.ViewCount from answers_a a, train t where a.ParentId = t.id;
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_train" into table train columns terminated by ',' lines terminated by '\n';
truncate table train;
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_train" into table train columns terminated by ',' lines terminated by '\n';
truncate table test;
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_test" into table test columns terminated by ',' lines terminated by '\n';
create table questions_aa as select a.Id, a.Body, a.ParentId, t.ViewCount from answers_a a, train t where a.ParentId = t.id;
ls
create table questions_aa as select q.Id, q.Title, q.Body, q.AcceptedAnswer, t.ViewCount from questions_a q, test t where q.Id = t.id;
create table questions_aa as select q.Id, q.Title, q.Body, q.AcceptedAnswerId, t.ViewCount from questions_a q, test t where q.Id = t.id;
alter table test add unique index qid (Id);
t
truncate train;
truncate test;
alter table questions_s change column `qid` to `Id` int(11);
alter table `questions_s` change column `qid` to `Id` int(11);
alter table `questions_s` change column `qid` `Id` int(11);
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_test" into table test columns terminated by ',' lines terminated by '\n';
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_train" into table train columns terminated by ',' lines terminated by '\n';
create table train_s like trian;
create table train_s like train;
create table test_s like test_s;
create table test_s like test;
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_train" into table train_s columns terminated by ',' lines terminated by '\n';
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/id_viewcount_test" into table test_s columns terminated by ',' lines terminated by '\n';
create table answers_s_train as select a.*, t.ViewCount from answers_s a, train_s t where a.ParentId = t.id;
create table answers_s_train as select a.*, t.ViewCount2 from answers_s a, train_s t where a.ParentId = t.id;
create table nswers_s_train as select a.*, t.ViewCount vc from answers_s a, train_s t where a.ParentId = t.id;
truncate train;
truncate test;
truncate train_s;
truncate test_s;
create table answers_a_train as select a.*, t.ViewCount from answers_s a, train_s t where a.ParentId = t.id;
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/questions_a_test" into table test columns terminated by ',' lines terminated by '\n';
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/questions_a_train" into table train columns terminated by ',' lines terminated by '\n';
create table answers_a_train as select a.*, t.ViewCount as TrainViewCount from answers_a a, train t where a.ParentId = t.id;
create table questions_a_test as select q.*, t.Viecreate table questions_a_test as select q.*, t.ViewCount as TestViewCount from questions_a q, test t where q.Id = t.id;wCount as TestViewCount from questions_a q, test t where q.Id = t.id;
alter table test drop index qid;
create table questions_a_test as select q.*, t.ViewCount as TestViewCount from questions_a q, test t where q.Id = t.id;
create table questions_a_test_train as select q.*, t.ViewCount as TrainViewCount from questions_a_test q, train t where q.Id = t.id;
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/questions_s_train" into table train_s columns terminated by ',' lines terminated by '\n';
load data local infile "/nfs/stak/users/ghadakcv/workspace/maple/questions_s_test" into table test_s columns terminated by ',' lines terminated by '\n';
create table answers_s_train as select a.*, t.ViewCount as TrainViewCount from answers_s a, train_s t where a.ParentId = t.id;
alter table test_s drop index qid;
create table questions_s_test_train as select q.*, tr.ViewCount as TrainViewCount, ts.ViewCount as TestViewCount from questions_s q, train_s tr, test_s ts where q.Id = tr.id and q.Id = ts.id;
create table answers_s_train_18 like answers_s_train;
create table Comments_18 like abtin.Comments;
rename table Comments_18 comments_18;
rename table Comments_18 to comments_18;
create ids_tmp as select Id from answers_s_train_18;
create table ids_tmp as select Id from answers_s_train_18;
create index id_index on `ids_tmp`(`Id`);
create index pid on `abtin.Comments`(`PostId`);
create index pid on `Comments`(`PostId`);
create table comments_18 select c.* from abtin.Comments c, ids_tmp i where c.PostId = i.Id;
create table posthistory_18 like abtin.PostHistory;
create table votes_18 like abtin.Votes;
create postlinks like abtin.PostLinks;
create table postlinks like abtin.PostLinks;
rename table postlinks to postlinks_18;
rename table ids_tmp to answers_s_train_18_ids; 
create table abtin.answers_s_train_18 like stack_overflow.answers_s_train_18;
create table abtin.answers_s_train like stack_overflow.answers_s_train;
create table ids_tmp as select Id from answers_s_train_18;
create index ids_index on ids Id;
create index ids_index on ids_tmp(Id);
create table sub_article_24 like tbl_article_wiki13;
create table sub_image_24 like tbl_image_09;
create table sub_link_24 like tbl_link_09;
create table sub_article_link_24 like tbl_article_link_09;
create table sub_article_image_24 like tbl_article_image_09;
create table ids_24 as select id from tbl_article_wiki13 order by popularity desc limit 2866808;
create index id_index on ids_24(id);
truncate sub_image_24;
create table answers_s_recall as select a.* from answers a join questions_s q on a.ParentId = q.Id;
create table answers_s_recall like answers_s;
create table answers_s_recall as select a.Id, a.ParentId, a.ViewCount, a.Body, a.Score from answers a join questions_s q on a.ParentId = q.Id;
create index pid on questions_s.Id;
create index pid on questions_s(Id);
truncate answers_s_recall;
create table answers_s_recall as select a.Id, a.ParentId, a.ViewCount, a.Body, a.Score from answers a join questions_s q on a.ParentId = q.Id;
create table questions_s_recall like questions;
create table questions_s_recall as select q.Id, q.Title, q.AcceptedanswerId, q.Score from questions q where q.Id in (select Id from questions_s);
create table questions_s_recall as select q.Id, q.Title, q.AcceptedanswerId, q.Score from questions q, questions_s qs where q.Id = qs.Id;
create table questions_s_recall as select q.Id, q.Title, q.AcceptedanswerId, q.Score, q.ViewCount from questions q, questions_s qs where q.Id = qs.Id;
create index id on questions_s_recall(Id);
create index pid on answers_s_recall(ParentId);
create index id on answers_s_recall(Id);
rename answers_s_recall to answers_s_vote_recall;
rename table answers_s_recall to answers_s_vote_recall;
create table answers_s_recall as select a.*, q.TrianViewCount from answers a join questions_s_test_train q on a.ParentId = q.Id;
create table answers_s_recall as select a.*, q.TrainViewCount from answers a join questions_s_test_train q on a.ParentId = q.Id;
create index id on questions_s_test_train(Id);
create table answers_s_recall as select a.*, q.TrainViewCount from answers a join questions_s_test_train q on a.ParentId = q.Id where 
create index id on answers_s_recall(Id);
create index pid on answers_s_recall(ParentId);
ls
create table answers_s_recall as select a.*, q.TrainViewCount from answers a join questions_s_test_train q on a.ParentId = q.Id where Score > 2;
create table answers_s_recall as select a.*, q.TrainViewCount from answers a join questions_s_test_train q on a.ParentId = q.Id where a.Score > 2;
rename table answers_s_recall to answers_s_minscore2
create table answers_s_2 as (select a.Id, a.ParentId, a.TrainViewCount, a.Body from answers_s a) union (select b.Id, b.ParentId, b.TrainViewCount, b.Body from answers_s_minscore2);
create table answers_s_2 as (select a.Id, a.ParentId, a.TrainViewCount, a.Body from answers_s_train a) union (select b.Id, b.ParentId, b.TrainViewCount, b.Body from answers_s_minscore2);
create table answers_s_2 as (select a.Id, a.ParentId, a.TrainViewCount, a.Body from answers_s_train a) union (select b.Id, b.ParentId, b.TrainViewCount, b.Body from answers_s_minscore2 b);
create index trainviewcount on answers_s_2(TrianViewCount);
create index trainviewcount on answers_s_2(TrainViewCount);
create index pid on answers_s_2.ParentId;
create index pid on answers_s_2(ParentId);
create index id on answers_s_2(Id);
create fulltext index idx_1 on mem_article_1(title);
create fulltext index idx_1 on mem_article_1(text);
create fulltext index idx_2 on mem_article_1(text);
alter table mem_article_1 add fulltext index `fulltext` (`title`, `text`);
create fulltext index fdx on tbl_article_09(title, text);
create fulltext index on tbl_article_09(title,text);
create fulltext index fdx on tbl_article_09(title,text);
create fulltext index fdx on tbl_article_09(title,text);
create fulltext index fdx on tbl_article_09(title);
repair table tbl_article_09;
repair table tbl_article_09;
alter table tbl_wiki_09;
alter table tbl_article_09;
create fulltext index fdx on tbl_article_09(title);
create fulltext index fdx on tbl_article_09(title,text);
create fulltext index fdx on tbl_article_09(title,text);
create fulltext index fdx on tbl_article_wiki13(title,text);
repair tbl_article_wiki13;
create table tmp_link_pop as select l.id, a.popularity from tbl_article_09 a, tbl_article_link_09 al, tbl_link_09 l where a.id = al.article_id and ai.link_id = l.id;
create table tmp_link_pop as select l.id, a.popularity from tbl_article_09 a, tbl_article_link_09 al, tbl_link_09 l where a.id = al.article_id and al.link_id = l.id;
create table tmp_link_pop as select l.id, a.popularity from tbl_article_09 a, tbl_article_link_09 al, tbl_link_09 l where a.id = al.article_id and al.link_id = l.id;
create index idx tmp_link_pop(id);
create index idx on tmp_link_pop(id);
create table tbl_link_pop as select id, sum(popularity) from tmp_link_pop;
create table tbl_image_pop as select l.id, sum(a.popularity) from tbl_article_09 a, tbl_article_image_09 al, tbl_image_09 l where a.id = al.article_id and al.image_id = l.id group by a.id;
create table tbl_link_pop as select l.*, coalesce(p.sum(popular
create table tbl_link_pop as select l.*, coalesce(p.sum(popular jj;
alter table tbl_link_pop change `sum(popularity)` `pop`
create table tbl_link_pop2 as l.id l.url coalesce(p.pop,0) from tbl_link_09 l left join tbl_link_pop p on l.id = p.id;
create table tbl_link_pop2 as l.id, l.url, coalesce(p.pop,0) from tbl_link_09 l left join tbl_link_pop p on l.id = p.id;
create table tbl_link_pop2 as l.id l.url coalesce(p.pop,0) from tbl_link_09 l left join tbl_link_pop p on l.id = p.id;
create table tbl_link_pop2 select l.id l.url coalesce(p.pop,0) from tbl_link_09 l left join tbl_link_pop p on l.id = p.id;
create table tbl_link_pop2 as select l.id l.url coalesce(p.pop,0) from tbl_link_09 l left join tbl_link_pop p on l.id = p.id;
create table tbl_link_pop2 as select l.id, l.url, coalesce(p.pop,0) from tbl_link_09 l left join tbl_link_pop p on l.id = p.id;
create index idx on tbl_link_pop(id);
create table tbl_link_pop2 as select l.id, l.url, coalesce(p.pop,0) from tbl_link_09 l left join tbl_link_pop p on l.id = p.id;
create index idx on tbl_link_pop2(id);
alte table tbl_link_popo2 `coalesce(p.pop,0)` `pop`;
alter table tbl_link_popo2 change `coalesce(p.pop,0)` `pop`;
alter table tbl_link_popo2 change `coalesce(p.pop,0)` `pop` int(11);
alter table tbl_link_pop2 change `coalesce(p.pop,0)` `pop` int(11);
create src-idx on tbl_image_09_pagecount(src);
create index src-idx on tbl_image_09_pagecount(src);
create index idx on tbl_image_09_pagecount(src);
alter table tbl_image_09_pagecount alter column src varchar(255);
alter table tbl_image_09_pagecount modify column src varchar(255);
create index idx on tbl_image_09_pagecount(src);
create table tbl_image_09_pop as select t.id, t.src, t.popularity, r.src_tokenized src_tk, coalesce(r.pagecount-3mon,0) pop, coalesce(r.pagecount-norm,0) pop_norm from tbl_image_09 t left join tbl_image_09_pagecount r on t.src = r.src;
create table tbl_image_09_pop as select t.id, t.src, t.popularity, r.src_tokenized src_tk, coalesce(`r.pagecount-3mon`,0) pop, coalesce(`r.pagecount-norm`,0) pop_norm from tbl_image_09 t left join tbl_image_09_pagecount r on t.src = r.src;
create table tbl_image_09_pop as select t.id, t.src, t.popularity, r.src_tokenized src_tk, coalesce(`r`.`pagecount-3mon`,0) pop, coalesce(`r.pagecount-norm`,0) pop_norm from tbl_image_09 t left join tbl_image_09_pagecount r on t.src = r.src;
create table tbl_image_09_pop as select t.id, t.src, t.popularity, r.src_tokenized src_tk, coalesce(`r`.`pagecount-3mon`,0) pop, coalesce(`r`.`pagecount-norm`,0) pop_norm from tbl_image_09 t left join tbl_image_09_pagecount r on t.src = r.src;
create index id on tbl_image_09_pop(id);
create fulltext index on tbl_image_09_pop(src_tk);
create fulltext index src_tk on tbl_image_09_pop(src_tk);
rename table tbl_link_pop2 to tbl_link_pop;
rename tbl_image_09_pop to tbl_image_pop;
rename table tbl_image_09_pop to tbl_image_pop;
rename table tbl_image_pop to tbl_image_popsum;
rename table tbl_image_09_pop to tbl_image_pop;
create fulltext index url on tbl_link_pop(url);
create table tmp_link as select r.*, t.id article_id from tbl_link_pop r, tbl_article_link_09 s, tbl_article_09 t where r.id = s.link_id and s.article_id = t.id;
rename tmp_link to tbl_link_pop2;
rename table tmp_link to tbl_link_pop2;
create index id on tbl_link_pop2(id);
alter table tbl_image_popsum alter column `sum(a.popularity)` `pop` int(32);
alter table tbl_image_popsum change column `sum(a.popularity)` `pop` int(32);
create table tbl_image_pop2 as select r.*, coalesce(s.pop,0) from tbl_image_09_tk left join tbl_article_popsum s on r.id = s.id;
create table tbl_image_pop2 as select r.*, coalesce(s.pop,0) from tbl_image_09_tk left join tbl_image_popsum s on r.id = s.id;
create table tbl_image_pop2 as select r.*, coalesce(s.pop,0) from tbl_image_09_tk r left join tbl_image_popsum s on r.id = s.id;
create index id on tbl_image_popsum(id);
create table tbl_image_pop2 as select r.*, coalesce(s.pop,0) from tbl_image_09_tk r left join tbl_image_popsum s on r.id = s.id;
rename table tbl_image_pop to tbl_image_pop_all;
rename table tbl_image_pop2 to tbl_image_pop;
create table tbl_image_pop as select r.*, sum(t.popularity) pop from tbl_image_09_tk r, tbl_article_image_09 s, tbl_article_09 t where r.id = s.image_id and s.article_id = t.id;
create index id on tbl_image_pop(id);
create table sub_image_10 like tbl_image_09_tk;
alter table tbl_image_pop drop column caption;
create table sub_image_10 like tbl_image_pop;
create fulltext index fdx on sub_image_10(src);
create table sub_article_3 like tbl_article_09;
alter table sub_article_3 drop index fdx;
truncate sub_article_3;
create fulltext index on sub_article_3(title, text);
create fulltext index fdx on sub_article_3(title, text);
create table sub_link_6 like tbl_link_pop;
alter table sub_link_6 drop index url;
create fulltext index fdx on sub_link_6(url);
alter table tbl_article_wik13 drop index fdx;
alter table tbl_article_wiki13 drop index fdx;
create fulltext index fdx on tbl_article_wiki13(title,text);
create table sub_wiki13_1 like sub_article_wiki13;
create table sub_wiki13_1 like tbl_article_wiki13;
create table sub_wiki13_1 as select * from tbl_article_wiki13 order by popularity limit 1194503;
create table sub_wiki13_1 as select * from tbl_article_wiki13 order by popularity desc limit 1194503;
create index id on sub_wiki13_1;
create index id on sub_wiki13_1(id);
create fulltext index fdx on sub_article_wiki13(title,text);
create fulltext index fdx on sub_wiki13_1(title,text);
rename table tbl_aritcle_wiki13 to tbl_article_13;
rename table tbl_article_wiki13 to tbl_article_13;
create table sub_article_wiki13 as select id from tbl_article_wiki13 limit 1000;
create table sub_article_wiki13 as select id from tbl_article_wiki13 limit 1000;
create table temp as select id from tbl_article_wiki13 order by popularity desc limit 20;
careate table temp as select id from tbl_article_wiki13 limit 0;
careate table temp as select id from tbl_article_wiki13 limit 1;
create table temp as select id from tbl_article_wiki13 limit 0;
alter table tbl_link_pop change pop popularity;
alter table tbl_link_pop change pop popularity(int);
alter table tbl_link_pop change pop popularity int(11);
create table sub_article_image_09 like tbl_article_image_09;
alter table sub_article_image_09 drop index image_id;
create table sub_article_link_09 like tbl_article_link_09;
ls
lt
create table comments_pop as select c.*, sum(a.ViewCount) from answers_s left join comments c on a.Id = c.PostId group by c.Id;
create table comments_pop as select c.*, sum(a.ViewCount) from answers_s a left join comments c on a.Id = c.PostId group by c.Id;
create index Id on answers_s(Id);
create table comments_pop as select c.*, sum(a.ViewCount) from answers_s a join comments c on a.Id = c.PostId group by c.Id;
create table tags_pop as select t.*, sum(a.ViewCount) from answers_s a join tags t on a.Id = t.ExcerptPostId group by a.Id;
create index ParentId on answers_s(ParentId);
create table tags_pop as select t.*, sum(a.ViewCount) from answers_s a join tags t on a.ParentId = t.ExcerptPostId group by a.ParentId;
create table stack_overflow.MyTags as select Id, Tags from Posts where Tags is not null;
create table PostTags(PostId int, TagId int);
create index PostId on PostTags(PostId);
create index TagId on PostTags(TagId);
alter table comments_pop change `sum(a.ViewCount)` `popularity`;
alter table comments_pop change `sum(a.ViewCount)` `popularity` int(32);
create table tags_pop as t.*, sum(a.ViewCount) as popularity from answers_s a join abtin.P;
create table post_tags as select pt.* from answers_s a join abtin.PostTags pt on a.ParentId = pt.PostId;
create table tags_pop as t.*, sum(a.ViewCount) as popularity from answers_s a join post_tags pt on a.ParentId = ;
create index PostId on post_tags(PostId);
create table tags_pop as t.*, sum(a.ViewCount) as popularity from answers_s a join post_tags pt on a.ParentId = pt.PostId join tags t on pt.TagId = t.Id;
create table tags_pop as t.*, sum(a.ViewCount) popularity from answers_s a join post_tags pt on a.ParentId = pt.PostId join tags t on pt.TagId = t.Id;
create table tags_pop as select t.*, sum(a.ViewCount) as popularity from answers_s a join post_tags pt on a.ParentId = pt.PostId join tags t on pt.TagId = t.Id;
create table tags_pop as select t.*, sum(a.ViewCount) as popularity from answers_s a join post_tags pt on a.ParentId = pt.PostId join tags t on pt.TagId = t.Id;
create table tags_pop as select t.*, sum(a.ViewCount) as popularity from answers_s a join post_tags pt on a.ParentId = pt.PostId join tags t on pt.TagId = t.Id group by (a.Id);
create index Id on tags_pop(Id);
alter table tags_pop change `popularity` `ViewCount` int(32);
alter table comments_pop change `popularity` `ViewCount` int(32);
